dplearning/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  root 'posts#index'
  get '/posts',to: 'posts#show'
  post '/posts/create', to: 'posts#create'
  post "posts/:id/update", to: "posts#update", as: 'update'
end

dplearning/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

dplearning/app/models/post.rb
class Post < ApplicationRecord
 mount_uploader :image,ImageUploader
end

dplearning/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

dplearning/app/controllers/posts_controller.rb
class PostsController < ApplicationController
require "open3"
  def index
    @posts = Post.all.order(created_at: 'desc')
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def new
  end
  
  def create
    #save
    @post = Post.new(post_params)
    label_predict
    @post.save!
    #redirect
    redirect_to action: 'show'
  end

  def destroy
     @post = Post.find(params[:id])
     @post.remove_image!
     @post.save!
     @post.destroy
     redirect_to posts_path
  end
  private
    def post_params
       params.require(:post).permit(:title,:image)
    end
    def label_predict #pythonによるラベル予測(適切なパスに変更)
       file = "/home/y-sugiyama/rails/dplearning/public"+@post.image.to_s
       o,e,s = Open3.capture3("python /home/y-sugiyama/rails/image_predict.py #{file}")
       @post.pred = o
    end
end

dplearning/app/helpers/application_helper.rb
module ApplicationHelper
end

dplearning/app/helpers/posts_helper.rb
module PostsHelper
end

dplearning/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dplearning</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <h1><%= link_to image_tag('logo.png',class: 'logo'),root_path %></h1>
    <%= yield %>
    </div>
  </body>
</html>

dplearning/app/views/posts/index.html.erb
<h2>
  <%= link_to 'Add New', new_post_path, class:'header-menu' %>
  My Posts
</h2>
<ul>
<% @posts.each do |post| %>
<li>
<%= link_to post.title,post_path(post) %>
<%= link_to "[delete]", post_path(post), method: :delete,data:{confirm: "ほんとによろしいですか？"}%>
</li>
<%end%>
</ul>

dplearning/app/views/posts/new.html.erb
<h2>Add New Post</h2>
<%= form_for :post, url: posts_create_path  do |f| %>
  <p><%=f.label "タイトル" %><br><%= f.text_field :title, placeholder: 'タイトル' %></p>
  <p><%=f.label "画像をアップロード" %><br><%= f.file_field :image %></p>
  <p><%= f.submit value: '投稿' %></p>
<% end %>

dplearning/app/views/posts/show.html.erb
<h2><%= @post.title%></h2>
<p>path <%= @post.image %></p>
<p><%= image_tag @post.image.url %></p>
<p><%= @post.pred %></p>